# SPDX-License-Identifier: GPL-3.0-or-later
"""Point2CAD ComfyUI nodes."""

from .point2cad_nodes import (
    NODE_CLASS_MAPPINGS as POINT2CAD_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as POINT2CAD_NODE_DISPLAY_NAME_MAPPINGS
)

from .point2cad_wireframe_node import (
    NODE_CLASS_MAPPINGS as WIREFRAME_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as WIREFRAME_NODE_DISPLAY_NAME_MAPPINGS
)

NODE_CLASS_MAPPINGS = {
    **POINT2CAD_NODE_CLASS_MAPPINGS,
    **WIREFRAME_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **POINT2CAD_NODE_DISPLAY_NAME_MAPPINGS,
    **WIREFRAME_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
